### ISSUE TITLE
Some concerns about the licenses

### ISSUE THREAD

**Issue by epiccakeking** [darkwater4213/aops-desktop#10]
Your code contains AoPS Enhanced so you need the LICENSE file for AoPS Enhanced.
Your code contains AoPS Master Script. I'm not really sure whether you need to keep the LICENSE file for that since it has the license listed in the header, but it is probably safer to add the LICENSE file.
Your license file is only in the docs folder, which is strange unless you are only licensing the docs under the GPL?
Your repo contains several files which are presumably copyright of AoPS. Are you sure you can use them (especially if you are using the GPL)?

**Comment by darkwater4213** [comment]
> Your code contains AoPS Enhanced so you need the LICENSE file for AoPS Enhanced.  

Okay, duly noted. Will do.

> Your code contains AoPS Master Script. I'm not really sure whether you need to keep the LICENSE file for that since it has the license listed in the header, but it is probably safer to add the LICENSE file.  

Ditto.

> Your license file is only in the docs folder, which is strange unless you are only licensing the docs under the GPL?  

I hadn't thought about that, thanks for pointing it out.

> Your repo contains several files which are presumably copyright of AoPS. Are you sure you can use them (especially if you are using the GPL)?  

Good point. I have a modified version of GPL I can use for giving copyright/credit to whomever it belongs to, but I haven't actually run it by a lawyer yet, so I wouldn't know if it would work. Perhaps I should just ask on AoPS...

Sorry I didn't see this earlier, I'll take care of all this as soon as I can.

Edit: fixed the goofy quotes.

**Comment by darkwater4213** [comment]
There. All done except for the last one -- still need to talk to the AoPS mods.
